name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ] # 监听 main 分支的推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # 允许工作流写入仓库

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        keep_files: false  
